### ISSUE TITLE
This is not a bug or issue and you probably won't be able to add it, but...

### ISSUE THREAD

**Issue by darkhog** [pvdstel/virtual-media-keys#1]
Are you aware of a similar program that displays clickable virtual media buttons on screen? So I can use it to easily change music while drawing on my tablet. Doesn't have to look nice.

**Comment by pvdstel** [comment]
I haven't seen anything like that, but I suppose something like that wouldn't be too hard to create. Not sure if I have time for it, but I might be able to create something. Are you using Windows?

**Comment by pvdstel** [comment]
See https://github.com/pvdstel/virtual-media-keys/releases/tag/v0.3 for a download 😉

**Comment by pvdstel** [comment]
It looks like the screenshot below and behaves similarly to the Windows on-screen keyboard. Resize margins and drag area are extra large for touch. The color will match your Windows accent color.

![image](https://user-images.githubusercontent.com/17430732/45925546-94522600-bee5-11e8-82d8-da1ce1177c2e.png)

**Comment by darkhog** [comment]
Thanks! Was about to roll my own when I saw your message.
