### ISSUE TITLE
UI: Add a single-row view

### ISSUE THREAD

**Issue by darkhog** [pvdstel/virtual-media-keys#4]
Not as separate EXE, but once user stretches the window enough (think what happens when you cheange width of a toolbar in MS OFFICE or about how words are wrapped in a text editor). And perhaps launch in a single row by default. Why? Because dual rows are too big and obstruct some important parts of the window (I'm fine with them obstructing titlebar and some of menu bar, but that's about it).

**Comment by pvdstel** [comment]
In the meantime I've been making some minor improvements to the UI such as the option to hide the title bar by right clicking (should be press and hold on touch but I'm not 100% sure). Maybe try one of the new releases to see if they work for you.

I don't have much time to work on this tool for the next couple of days. If you really want/need it you may consider making a pull request.
